### ISSUE TITLE
Promotion with release specified assumes the first matching appname is the one to be promoted

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x-plugins/jx-promote#387]
In an example where I have the helmfile (with unnecessary fields removed)
```
releases:
- chart: dev/myapp
  name: myapp
- chart: dev/myapp
  name: myapp-beta
```

And I promote like so
`jx promote --release myapp-beta` with the version 1.0.0

The helmfile will be wrongly edited so the resulting helmfile would look like so

```
releases:
- chart: dev/myapp
  name: myapp
  version: 1.0.0
- chart: dev/myapp
  name: myapp-beta
```

The correct helmfile should look like

```
releases:
- chart: dev/myapp
  name: myapp
- chart: dev/myapp
  name: myapp-beta
  version: 1.0.0
```

Pullable PR to play around with (if you require it)
https://github.com/jenkins-x-plugins/jx-promote/pull/388
